### ISSUE TITLE
Permission denied on image replacement

### ISSUE THREAD

**Issue by Ace2213** [humhub/humhub-modules-wiki#105]
When editing a wiki page, if you remove an image and add a new one (via Ctrl+V) it triggers a 500 internal server error and the image does not get added. You have to save the page then edit it again to add the new image. 

`yii\base\Exceptionyii\base\ErrorException: mkdir(): Permission denied in /var/www/html/hub/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php:640 Stack trace: #0 [internal function]: yii\base\ErrorHandler->handleError(2, 'mkdir(): Permis...', '/var/www/html/h...', 640, Array) #1 /var/www/html/hub/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(640): mkdir('/var/www/html/h...', 484) #2 /var/www/html/hub/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(637): yii\helpers\BaseFileHelper::createDirectory('/var/www/html/h...', 484, true) #3 /var/www/html/hub/protected/humhub/modules/file/components/StorageManager.php(156): yii\helpers\BaseFileHelper::createDirectory('/var/www/html/h...', 484, true) #4 /var/www/html/hub/protected/humhub/modules/file/components/StorageManager.php(56): humhub\modules\file\components\StorageManager->getPath() #5 /var/www/html/hub/protected/humhub/modules/file/components/StorageManager.php(80): humhub\modules\file\components\StorageManager->get('file') #6 /var/www/html/hub/protected/humhub/modules/file/models/FileUpload.php(49): humhub\modules\file\components\StorageManager->set(Object(yii\web\UploadedFile)) #7 /var/www/html/hub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(611): humhub\modules\file\models\FileUpload->afterSave(true, Array) #8 /var/www/html/hub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL) #9 /var/www/html/hub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL) #10 /var/www/html/hub/protected/humhub/modules/file/actions/UploadAction.php(95): yii\db\BaseActiveRecord->save() #11 /var/www/html/hub/protected/humhub/modules/file/actions/UploadAction.php(71): humhub\modules\file\actions\UploadAction->handleFileUpload(Object(yii\web\UploadedFile), true) #12 [internal function]: humhub\modules\file\actions\UploadAction->run() #13 /var/www/html/hub/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array) #14 /var/www/html/hub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array) #15 /var/www/html/hub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('upload', Array) #16 /var/www/html/hub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('file/file/uploa...', Array) #17 /var/www/html/hub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #18 /var/www/html/hub/index.php(25): yii\base\Application->run() #19 {main} Next yii\base\Exception: Failed to create directory "/var/www/html/hub/uploads/file/d/a": mkdir(): Permission denied in /var/www/html/hub/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php:645 Stack trace: #0 /var/www/html/hub/protected/vendor/yiisoft/yii2/helpers/BaseFileHelper.php(637): yii\helpers\BaseFileHelper::createDirectory('/var/www/html/h...', 484, true) #1 /var/www/html/hub/protected/humhub/modules/file/components/StorageManager.php(156): yii\helpers\BaseFileHelper::createDirectory('/var/www/html/h...', 484, true) #2 /var/www/html/hub/protected/humhub/modules/file/components/StorageManager.php(56): humhub\modules\file\components\StorageManager->getPath() #3 /var/www/html/hub/protected/humhub/modules/file/components/StorageManager.php(80): humhub\modules\file\components\StorageManager->get('file') #4 /var/www/html/hub/protected/humhub/modules/file/models/FileUpload.php(49): humhub\modules\file\components\StorageManager->set(Object(yii\web\UploadedFile)) #5 /var/www/html/hub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(611): humhub\modules\file\models\FileUpload->afterSave(true, Array) #6 /var/www/html/hub/protected/vendor/yiisoft/yii2/db/ActiveRecord.php(566): yii\db\ActiveRecord->insertInternal(NULL) #7 /var/www/html/hub/protected/vendor/yiisoft/yii2/db/BaseActiveRecord.php(678): yii\db\ActiveRecord->insert(true, NULL) #8 /var/www/html/hub/protected/humhub/modules/file/actions/UploadAction.php(95): yii\db\BaseActiveRecord->save() #9 /var/www/html/hub/protected/humhub/modules/file/actions/UploadAction.php(71): humhub\modules\file\actions\UploadAction->handleFileUpload(Object(yii\web\UploadedFile), true) #10 [internal function]: humhub\modules\file\actions\UploadAction->run() #11 /var/www/html/hub/protected/vendor/yiisoft/yii2/base/Action.php(94): call_user_func_array(Array, Array) #12 /var/www/html/hub/protected/vendor/yiisoft/yii2/base/Controller.php(157): yii\base\Action->runWithParams(Array) #13 /var/www/html/hub/protected/vendor/yiisoft/yii2/base/Module.php(528): yii\base\Controller->runAction('upload', Array) #14 /var/www/html/hub/protected/vendor/yiisoft/yii2/web/Application.php(103): yii\base\Module->runAction('file/file/uploa...', Array) #15 /var/www/html/hub/protected/vendor/yiisoft/yii2/base/Application.php(386): yii\web\Application->handleRequest(Object(humhub\components\Request)) #16 /var/www/html/hub/index.php(25): yii\base\Application->run() #17 {main}`

**Comment by Ace2213** [comment]
Might not necessarily be when replacing. I just experienced again in a different way.

I was creating a page and copied contents into it (including images) and deleted the images so I can edit them and re-add them.

This time, expecting the bug, I saved without the images and clicked edit again to re-add them.

When adding the images, I got the error again. I had to save and re-edit to make it work.

I guess you have to save after you see the error and then it will work again.

**Comment by Ace2213** [comment]
It would seem that it's possible to bypass this error by inserting the image into a different part of the content. Very strange. Trying to insert it into the same spot failed despite saving and re-editing several times. I was only able to get it to work by inserting it a line lower.
